# -*- coding: utf-8 -*-
"""W1_Data_Wrangling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cv3_bgycwxjvEPYDH0R1UfLuu05Omv-v
"""

# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
#NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np

df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")
df.head(10)

#identify and calculate percentage of missing value

df.isnull().sum()/df.count()*100

df.dtypes

#calculate number of launches for each site

df['LaunchSite'].value_counts()

#calculate number and occurence for each orbit

df['Orbit'].value_counts()

#calculate number and occurence of mission outcome of the orbit

landing_outcomes = df['Outcome'].value_counts()
landing_outcomes

for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

#create landing outcome

# landing_class = 0 if bad_outcome
# landing_class = 1 otherwise

df_landing_transform = df['Outcome'].replace(
    {'True ASDS': 1,
     'None None': 0,
     'True RTLS': 1,
     'False ASDS': 0,
     'True Ocean': 1,
     'False Ocean': 0,
     'None ASDS': 0,
     'False RTLS': 0,
     })

df_landing_transform

#landing_class
df['Class']=df_landing_transform

df[['Class']].head(8)

df.head(5)

df["Class"].mean()

df.to_csv("dataset_part_2.csv", index=False)